services:

  resource:
     class: Rest\Bundle\Classes\ResourceManager
     arguments: [@service_container, @doctrine.orm.entity_manager, @serializer, @doctrine.valueobject]
     lazy: true

  doctrine.valueobject:
     class: Rest\Bundle\Classes\DoctrineValueObject
     arguments: [@service_container, @doctrine.orm.entity_manager]
     lazy: true
