schema:
    resource: "@SchemaBundle/Controller/"
    type:     annotation
    prefix:   /

rest:
    resource: "@RestBundle/Controller/"
    type:     annotation
    prefix:   /

oauth2_server:
    resource: "@OAuth2ServerBundle/Controller/"
    type:     annotation
    prefix:   /